# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил:
- Глазырин Александр Сергеевич
- ИНО ОЗБ ПОАС-22-1

| Задание   | Сам_раб |
|-----------|---------|
| Задание 1 | +       |
| Задание 2 | +       |
| Задание 3 | +       |
| Задание 4 | +       |
| Задание 5 | +       |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Самостоятельная работа 1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор. Подсказка: необходимо использовать модуль time Декоратор необходимо использовать для этой функции:
![Task10_1](./img/Task10_1.png)
### Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы. Также на этом примере можете посмотреть, что решение задач через рекурсию не всегда является хорошей идеей. Поскольку решение Фибоначчи для 100 с использованием рекурсии и без динамического программирования решается более десяти секунд, а решение точно такой же задачи, но через цикл for еще и для 200, занимает меньше 1 секунды.

```python
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.perf_counter()
        result = func(*args, **kwargs)
        end_time = time.perf_counter()
        elapsed_time = end_time - start_time
        print(f"Функция {func.__name__} выполнена за {elapsed_time:.6f} секунд")
        return result
    return wrapper

@timing_decorator
def calculate_sum(n):
    return sum(range(1, n + 1))

print(calculate_sum(1000000))
```
### Результат
![Lab10_1](./img/Lab10_1.png)

## Самостоятельная работа 2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file_content(filename):
    try:
        with open(filename, 'r') as file:
            content = file.read().strip()
            if not content:
                raise ValueError("файл пустой")
            return content
    except FileNotFoundError:
        print(f"Файл {filename} не найден.")
    except ValueError as e:
        print(e)

with open('empty_file.txt', 'w') as file:
    pass

with open('non_empty_file.txt', 'w') as file:
    file.write("Привет, мир!")

print(read_file_content('empty_file.txt'))

print(read_file_content('non_empty_file.txt'))
```
### Результат
![Lab10_2](./img/Lab10_2.png)

## Самостоятельная работа 3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

```python
def add_two(user_input):
    try:
        result = round(2 + float(user_input))
        print(f"Результат сложения: {result}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

add_two("5")
add_two("7.01")
add_two("abcsadadwe")
add_two("13")
```
### Результат
![Lab10_3](./img/Lab10_3.png)

## Самостоятельная работа 4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class TypeCheckDecorator:
    def __init__(self, return_type):
        self.return_type = return_type

    def __call__(self, func):
        def wrapper(*args, **kwargs):
            result = func(*args, **kwargs)
            if not isinstance(result, self.return_type):
                raise ValueError(f"Возвращаемое значение должно быть типа {self.return_type}, получен {type(result)}")
            return result

        return wrapper

@TypeCheckDecorator(str)
def get_greeting(name):
    return f"Привет, {name}!"

@TypeCheckDecorator(list)
def get_numbers(n):
    return list(range(n))


print(get_greeting("Алеша"))
print(get_numbers(5))

try:
    print(get_greeting(123))
except ValueError as e:
    print(e)

try:
    print(get_numbers("abcsdasd"))
except ValueError as e:
    print(e)
```
### Результат
![Lab10_4](./img/Lab10_4.png)

## Самостоятельная работа 5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class ValueTooLargeError(Exception):
    def __init__(self, value, max_value):
        self.value = value
        self.max_value = max_value
        self.message = f"Значение {value} превышает максимальное допустимое значение {max_value}"
        super().__init__(self.message)

def check_value(value, max_value):
    if value > max_value:
        raise ValueTooLargeError(value, max_value)

def process_data(data, threshold):
    for value in data:
        try:
            if value > threshold:
                raise ValueTooLargeError(value, threshold)
        except ValueTooLargeError as e:
            print(f"Ошибка обработки данных: {e}")

# Первый фрагмент
try:
    check_value(100, 50)
except ValueTooLargeError as e:
    print(e)

# Второй фрагмент
data = [30, 40, 60, 70]
threshold = 50
process_data(data, threshold)
```
### Результат
![Lab10_5](./img/Lab10_5.png)

